/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LangSelect: typeof import('./src/components/LangSelect/LangSelect.vue')['default']
    Navigation: typeof import('./src/components/Navigation/Navigation.vue')['default']
  }
}
